export const hardcodedRecipes = [
  {
    ingredients: [],
    categories: [],
    _id: "5eef2fde01c87f5c771944d9",
    title: "Pilnas postman test receptas",
    preparation: "Pilnai uzpildytas postman test user receptas",
    notes:
      "nepamirsti papildyti sio requesto laukelius, jei sugalvosiu pakeisti recepta",
    time: "2h",
    portions: 3,
    image: "/soup.jpg",
    summary: "ilgas receptas",
    author: "TestUser",
    date: 1592733662272,
    recipeId: 11,
    slug: "pilnas-postman-test-receptas-11",
    __v: 0,
  },
  {
    ingredients: [],
    categories: [],
    _id: "5efb9e4dc82f550024cc17d0",
    title: "bandom pakeist pavadinima",
    preparation: "biski to biski ano ir vuala aad",
    notes: "",
    summary: "",
    image: "/soup2.jpg",
    time: "",
    portions: null,
    author: "TestUser",
    date: 1593548365774,
    recipeId: 13,
    slug: "lets-post-one-more-13",
    __v: 0,
  },
  {
    ingredients: [],
    categories: [],
    _id: "5f02e7807eb2a4137e7805b1",
    title: "Pilnas postman test receptas",
    preparation: "Pilnai uzpildytas postman test user receptas",
    notes:
      "nepamirsti papildyti sio requesto laukelius, jei sugalvosiu pakeisti recepta",
    time: "2h",
    portions: 3,
    image: "",
    summary: "ilgas receptas",
    author: "TestUser",
    date: 1594025856029,
    recipeId: 15,
    slug: "pilnas-postman-test-receptas-15",
    __v: 0,
  },
  {
    ingredients: [],
    categories: [],
    _id: "5f02e954f370ce0024a91a5e",
    title: "dar vienas",
    preparation: "dar",
    notes: "",
    summary: "",
    image: "/stake.jpg",
    time: "",
    portions: null,
    slug: "dar-vienas-17",
    author: "TestUser",
    date: 1594026324312,
    recipeId: 17,
    __v: 0,
  },
  {
    ingredients: [],
    categories: [],
    _id: "5f02e97af370ce0024a91a5f",
    title: "upup",
    preparation: "up",
    notes: "",
    summary: "",
    image: "/burger2.jpg",
    time: "",
    portions: null,
    slug: "upup-18",
    author: "TestUser",
    date: 1594026362442,
    recipeId: 18,
    __v: 0,
  },
  {
    ingredients: [],
    categories: [],
    _id: "5f02eae5f370ce0024a91a60",
    title: "opa",
    preparation: "opa",
    notes: "",
    summary: "",
    image: "/lentil.jpeg",
    time: "",
    portions: null,
    slug: "opa-19",
    author: "TestUser",
    date: 1594026725893,
    recipeId: 19,
    __v: 0,
  },
];
